using FluentAssertions;
using MetisPlaywright.Pages;

namespace MetisPlaywright.Tests
{
    public class CompanyDetailsTests : BaseTest
    {
        [Test]
        public async Task T01_CompanyDetails_CreateNewCustomer_DefaultView()
        {
            const string expectedTitle = "Create New Customer Account";

            var companyDetailsPage = new CompanyDetailsPage(Fixture.Page);
            await companyDetailsPage.OpenCreateNewCustomerPageForAutoTests1Async();
            var actualTitle = await companyDetailsPage.GetPageTitleAsync();
            actualTitle.Should().Be(expectedTitle, "Create New Customer Account page should open after clicking Create Customer Account");
        }

        [Test]
        public async Task T02_CompanyDetails_IndustryDropdownOptions()
        {
            var expectedOptions = new List<string>
            {
                "3D Printing & Additive Manufacturing",
                "Accounting & Auditing",
                "Advertising & Marketing",
                "Aerospace & Defence",
                "Agriculture & Farming",
                "AI & Machine Learning",
                "Airlines & Aviation",
                "Architecture & Urban Planning",
                "Astrology & Psychic Services",
                "Auto Repair & Maintenance",
                "Automotive Manufacturing",
                "Banking & Financial Services",
                "Bioinformatics & Genomics",
                "Biotechnology & Life Sciences",
                "Blockchain & Cryptocurrency",
                "Car Rental & Leasing",
                "Charities & Nonprofits",
                "Chemicals & Petrochemicals",
                "Civil Engineering & Infrastructure",
                "Cloud Computing",
                "Commercial & Industrial Construction",
                "Commercial Real Estate",
                "Consumer Electronics & Appliances",
                "Corporate Training & E-Learning",
                "Cybersecurity",
                "Defence & Military",
                "Digital Media & Influencers",
                "E-commerce",
                "Electric & Gas Utilities",
                "Electric Vehicles & Battery Technology",
                "Electronics & Semiconductors",
                "Environmental Consulting & Services",
                "Event Planning & Conferences",
                "Fashion & Apparel Retail",
                "Film & Television Production",
                "Fire & Rescue Services",
                "Fishing & Aquaculture",
                "Fitness & Gyms",
                "Food & Beverage Manufacturing",
                "Forestry & Timber",
                "Funeral & End-of-Life Services",
                "Government & Public Administration",
                "Higher Education & Universities",
                "Home & Furniture Retail",
                "Home Improvement & DIY Retail",
                "Hospitals & Healthcare Facilities",
                "Hotels & Accommodation",
                "Insurance & Risk Management",
                "International Development & Aid",
                "Investment Management & Private Equity",
                "IT Services & Consulting",
                "Law Enforcement",
                "Legal Services",
                "Machinery & Industrial Equipment",
                "Management Consulting",
                "Medical Devices & Equipment",
                "Mental Health Services",
                "Mining & Quarrying",
                "Music & Performing Arts",
                "Oil & Gas Extraction",
                "Outdoor & Adventure Activities",
                "Paper & Pulp",
                "Payment Processing & FinTech",
                "Personal Care & Cosmetics",
                "Pharmaceuticals & Biotechnology",
                "Plastics & Rubber Manufacturing",
                "Primary & Secondary Education",
                "Private Investigation",
                "Private Security Services",
                "Professional Sports & Athletics",
                "Property Development",
                "Public Relations & Communications",
                "Publishing & Print Media",
                "Rail Transport",
                "Real Estate Investment & Asset Management",
                "Recruitment & HR Services",
                "Recycling & Waste Reduction",
                "Renewable Energy Production",
                "Residential Construction",
                "Residential Real Estate",
                "Restaurants & Food Services",
                "Ride-Hailing & Mobility Platforms",
                "Road Transport & Logistics",
                "Scientific Research & Development",
                "Shipping & Maritime",
                "Software Development",
                "Space Exploration & Aerospace Tech",
                "Steel & Metal Production",
                "Supermarkets & Grocery Retail",
                "Sustainable & Green Tech",
                "Tattoo & Body Art Services",
                "Telecommunications & Networking",
                "Textiles & Apparel",
                "Translation & Interpretation Services",
                "Travel Agencies & Tour Operators",
                "Veterinary Services",
                "Video Games & Esports",
                "Warehousing & Supply Chain Management",
                "Water Supply & Waste Management",
                "Wholesale Distribution"
            };

            var companyDetailsPage = new CompanyDetailsPage(Fixture.Page);
            await companyDetailsPage.OpenCreateNewCustomerPageForAutoTests1Async();
            var options = await companyDetailsPage.GetIndustryDropdownOptionsAsync();
            options.Should().NotBeEmpty("Industry dropdown should contain at least one option");
            foreach (var expected in expectedOptions)
            {
                options.Should().Contain(expected, $"Industry dropdown should contain option '{expected}'");
            }
        }
        [Test]
        public async Task T03_CompanyDetails_EmptyFields()
        {
            const string expectedCustomerNameError = "'Name' is required.";
            const string expectedIndustryError = "'Industry Type' is required.";

            var companyDetailsPage = new CompanyDetailsPage(Fixture.Page);
            await companyDetailsPage.OpenCreateNewCustomerPageForAutoTests1Async();
            await companyDetailsPage.ClickSaveAsync();
            await companyDetailsPage.ExpectCustomerNameErrorAsync(expectedCustomerNameError);
            await companyDetailsPage.ExpectIndustryErrorAsync(expectedIndustryError);
        }
        [Test]
        public async Task T04_CompanyDetails_BusinessTypeDropdownOptions()
        {
            var expectedOptions = new List<string>
            {
                "Agriculture & Food Production",
                "Charitable Incorporated Organisation (CIO)",
                "Co-operative (Co-op)",
                "Community Interest Company (CIC)",
                "Construction & Real Estate",
                "Creative & Media",
                "Education & Training",
                "Energy & Utilities",
                "Finance & Banking",
                "Guarantee Company (Ltd by Guarantee)",
                "Healthcare & Pharmaceuticals",
                "Hospitality & Tourism",
                "Industrial and Provident Society (IPS)",
                "Legal & Professional Services",
                "Limited Liability Partnership (LLP)",
                "Manufacturing & Engineering",
                "Non-Profit & Charity",
                "Partnership",
                "Private Limited Company (Ltd)",
                "Public Sector & Government",
                "Retail & E-commerce",
                "Royal Charter Company",
                "Scottish Limited Partnership (SLP)",
                "Sole Trader",
                "Technology & Software",
                "Transportation & Logistics",
                "Unlimited Company"
            };

            var companyDetailsPage = new CompanyDetailsPage(Fixture.Page);
            await companyDetailsPage.OpenCreateNewCustomerPageForAutoTests1Async();
            var options = await companyDetailsPage.GetBusinessTypeDropdownOptionsAsync();
            options.Should().NotBeEmpty("Business Type dropdown should contain at least one option");
            foreach (var expected in expectedOptions)
            {
                options.Should().Contain(expected, $"Business Type dropdown should contain option '{expected}'");
            }
        }
        [Test]
        public async Task T05_CompanyDetails_CountryDropdownOptions()
        {
            var expectedOptions = new List<string>
            {
                "Afghanistan",
                "Åland Islands",
                "Albania",
                "Algeria",
                "American Samoa",
                "Andorra",
                "Angola",
                "Anguilla",
                "Antigua & Barbuda",
                "Argentina",
                "Armenia",
                "Aruba",
                "Australia",
                "Austria",
                "Azerbaijan",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belgium",
                "Belize",
                "Benin",
                "Bermuda",
                "Bhutan",
                "Bolivia",
                "Bonaire, Sint Eustatius and Saba",
                "Bosnia & Herzegovina",
                "Botswana",
                "Brazil",
                "British Indian Ocean Territory",
                "British Virgin Islands",
                "Brunei",
                "Bulgaria",
                "Burkina Faso",
                "Burundi",
                "Cabo Verde",
                "Cambodia",
                "Cameroon",
                "Canada",
                "Cayman Islands",
                "Central African Republic",
                "Chad",
                "Chile",
                "China",
                "Christmas Island",
                "Cocos (Keeling) Islands",
                "Colombia",
                "Comoros",
                "Congo",
                "Congo (DRC)",
                "Cook Islands",
                "Costa Rica",
                "Côte d’Ivoire",
                "Croatia",
                "Cuba",
                "Curaçao",
                "Cyprus",
                "Czechia",
                "Denmark",
                "Djibouti",
                "Dominica",
                "Dominican Republic",
                "Ecuador",
                "Egypt",
                "El Salvador",
                "Equatorial Guinea",
                "Eritrea",
                "Estonia",
                "Eswatini",
                "Ethiopia",
                "Europe",
                "Falkland Islands",
                "Faroe Islands",
                "Fiji",
                "Finland",
                "France",
                "French Guiana",
                "French Polynesia",
                "Gabon",
                "Gambia",
                "Georgia",
                "Germany",
                "Ghana",
                "Gibraltar",
                "Greece",
                "Greenland",
                "Grenada",
                "Guadeloupe",
                "Guam",
                "Guatemala",
                "Guernsey",
                "Guinea",
                "Guinea-Bissau",
                "Guyana",
                "Haiti",
                "Honduras",
                "Hong Kong SAR",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran",
                "Iraq",
                "Ireland",
                "Isle of Man",
                "Israel",
                "Italy",
                "Jamaica",
                "Japan",
                "Jersey",
                "Jordan",
                "Kazakhstan",
                "Kenya",
                "Kiribati",
                "Korea",
                "Kosovo",
                "Kuwait",
                "Kyrgyzstan",
                "Laos",
                "Latin America",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Macao SAR",
                "Madagascar",
                "Malawi",
                "Malaysia",
                "Maldives",
                "Mali",
                "Malta",
                "Marshall Islands",
                "Martinique",
                "Mauritania",
                "Mauritius",
                "Mayotte",
                "Mexico",
                "Micronesia",
                "Moldova",
                "Monaco",
                "Mongolia",
                "Montenegro",
                "Montserrat",
                "Morocco",
                "Mozambique",
                "Myanmar",
                "Namibia",
                "Nauru",
                "Nepal",
                "Netherlands",
                "New Caledonia",
                "New Zealand",
                "Nicaragua",
                "Niger",
                "Nigeria",
                "Niue",
                "Norfolk Island",
                "North Korea",
                "North Macedonia",
                "Northern Mariana Islands",
                "Norway",
                "Oman",
                "Pakistan",
                "Palau",
                "Palestinian Authority",
                "Panama",
                "Papua New Guinea",
                "Paraguay",
                "Peru",
                "Philippines",
                "Pitcairn Islands",
                "Poland",
                "Portugal",
                "Puerto Rico",
                "Qatar",
                "Réunion",
                "Romania",
                "Russia",
                "Rwanda",
                "Samoa",
                "San Marino",
                "São Tomé & Príncipe",
                "Saudi Arabia",
                "Senegal",
                "Serbia",
                "Seychelles",
                "Sierra Leone",
                "Singapore",
                "Sint Maarten",
                "Slovakia",
                "Slovenia",
                "Solomon Islands",
                "Somalia",
                "South Africa",
                "South Sudan",
                "Spain",
                "Sri Lanka",
                "St Helena, Ascension, Tristan da Cunha",
                "St. Barthélemy",
                "St. Kitts & Nevis",
                "St. Lucia",
                "St. Martin",
                "St. Pierre & Miquelon",
                "St. Vincent & Grenadines",
                "Sudan",
                "Suriname",
                "Svalbard & Jan Mayen",
                "Sweden",
                "Switzerland",
                "Syria",
                "Taiwan",
                "Tajikistan",
                "Tanzania",
                "Thailand",
                "Timor-Leste",
                "Togo",
                "Tokelau",
                "Tonga",
                "Trinidad & Tobago",
                "Tunisia",
                "Turkey",
                "Turkmenistan",
                "Turks & Caicos Islands",
                "Tuvalu",
                "U.S. Outlying Islands",
                "U.S. Virgin Islands",
                "Uganda",
                "Ukraine",
                "United Arab Emirates",
                "United Kingdom",
                "United States",
                "Uruguay",
                "Uzbekistan",
                "Vanuatu",
                "Vatican City",
                "Venezuela",
                "Vietnam",
                "Wallis & Futuna",
                "World",
                "Yemen",
                "Zambia",
                "Zimbabwe"
            };

            var companyDetailsPage = new CompanyDetailsPage(Fixture.Page);
            await companyDetailsPage.OpenCreateNewCustomerPageForAutoTests1Async();
            var options = await companyDetailsPage.GetCountryDropdownOptionsAsync();
            options.Should().NotBeEmpty("Country dropdown should contain at least one option");
            foreach (var expected in expectedOptions)
            {
                options.Should().Contain(expected, $"Country dropdown should contain option '{expected}'");
            }
        }
    }
}
